services:
  - type: static
    name: chemithasathsilu
    repo: https://github.com/chemitha/chemithasathsilu
    branch: main
    buildCommand: ""
    publishPath: public
    redirects:
      # 1. Redirect old onrender domain to your custom domain (with 301)
      - from: http://chemithasathsilu.onrender.com/*
        to: https://chemitha.com/*
        status: 301
      - from: https://chemithasathsilu.onrender.com/*
        to: https://chemitha.com/*
        status: 301

      - from: /showcase
        to: /showcase.html
        status: 200
      - from: /404
        to: /404.html
        status: 404