services:
  - type: static
    name: chemithasathsilu
    repo: https://github.com/chemitha/chemithasathsilu
    branch: main
    buildCommand: ""
    publishPath: public
    redirects:
      - from: /showcase
        to: https://labs.chemitha.com/
        status: 301
      - from: /404
        to: /404.html
        status: 404
